# 1. Objective
The objective of this notebook is to prepare the raw dataset for subsequent analytical stages.

The preparation process is based on the findings from the Data Assessment stage and focuses on applying necessary data cleaning, standardization, and feature engineering while preserving the integrity of the original observations.

The prepared dataset will be validated before being used for exploratory analysis, statistical analysis, customer segmentation, SQL analytics, and visualization.

# 2. Load Raw Data
The raw dataset is loaded directly from the project's raw data directory. The original file is preserved unchanged, and all
preparation steps are performed on a working copy.

In [3]:
import pandas as pd

In [4]:
df =  pd.read_csv("../data/raw/trendOne_raw.csv")

In [5]:
row_c, col_c = df.shape
print(f"Number of rows: {row_c}")
print(f"Number of columns: {col_c}")

Number of rows: 3900
Number of columns: 18

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df_prep = df.copy()
df_prep.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

## 3. Data Preparation Plan

|No | Assessment Finding                            | Preparation Action               | Reason                                       |
|:-:|-----------------------------------------------|----------------------------------|----------------------------------------------|
|1  | Column name not follow industry best practice | Make it lowercase and snake_case | To prevent errors and improve ease of use    |
|2  | Missing values on review rating               | Imputation required              | To clean and standardize the data format     |
|3  | Derived analytical groups required            | Create analytical features       | To get a broad overview or insights          |

## 4. Data Cleaning

### Standardize columns name

In [12]:
# Standardize columns name

df_prep.columns = df_prep.columns.str.lower()
df_prep.columns = df_prep.columns.str.replace(' ', '_')

df_prep = df_prep.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount_usd'})
df_prep.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

The column names shown above have been updated to follow standard naming conventions.

### Missing values data imputation

In [15]:
# Missing values data imputation
df_prep.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3863 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  promo_code_used         3900 non-null   str
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   str
 17  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [16]:
df_prep['review_rating'] = df_prep['review_rating'].fillna(df_prep['review_rating'].mean().round(1))
df_prep.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  promo_code_used         3900 non-null   str
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   str
 17  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

Missing values in the review_rating column have been imputed using the mean, leaving no null values remaining in the dataset.

## 5. Feature Engineering

### Age group
`Age Group` is created to support customer-level comparisons across age ranges.

The feature is derived from `Age` and will be used as a grouping variable in subsequent customer analysis. The original `Age` variable is retained to preserve the underlying numerical information.

In [20]:
bins = [17, 24, 34, 44, 54, 64, 70]
labels = ["18-24", "25-34", "35-44", "45-54", "55-64", "65-70"]

df_prep['age_group'] = pd.cut(
    df_prep["age"],
    bins=bins,
    labels=labels
)

I created these bins by taking into account the minimum and maximum age values, ensuring they focus strictly on the observed age range.

### Previous Purchases Group

In [23]:
bins=[-1, 5, 10, 20, float("inf")]
labels=["0-5", "6-10", "11-20", "21+"]

df_prep['previous_purchases_group'] = pd.cut(
    df_prep["previous_purchases"],
    bins=bins,
    labels=labels
)

I grouped the previous_purchases data to identify frequent buyers, which can serve as a valuable analytical insight.

### Region

In [26]:
df_prep['location'].unique()

<StringArray>
[      'Kentucky',          'Maine',  'Massachusetts',   'Rhode Island',
         'Oregon',        'Wyoming',        'Montana',      'Louisiana',
  'West Virginia',       'Missouri',       'Arkansas',         'Hawaii',
       'Delaware',  'New Hampshire',       'New York',        'Alabama',
    'Mississippi', 'North Carolina',     'California',       'Oklahoma',
        'Florida',          'Texas',         'Nevada',         'Kansas',
       'Colorado',   'North Dakota',       'Illinois',        'Indiana',
        'Arizona',         'Alaska',      'Tennessee',           'Ohio',
     'New Jersey',       'Maryland',        'Vermont',     'New Mexico',
 'South Carolina',          'Idaho',   'Pennsylvania',    'Connecticut',
           'Utah',       'Virginia',        'Georgia',       'Nebraska',
           'Iowa',   'South Dakota',      'Minnesota',     'Washington',
      'Wisconsin',       'Michigan']
Length: 50, dtype: str

In [27]:
state_region = {
    "Maine": "Northeast",
    "New Hampshire": "Northeast",
    "Vermont": "Northeast",
    "Massachusetts": "Northeast",
    "Rhode Island": "Northeast",
    "Connecticut": "Northeast",
    "New York": "Northeast",
    "New Jersey": "Northeast",
    "Pennsylvania": "Northeast",

    "Ohio": "Midwest",
    "Indiana": "Midwest",
    "Illinois": "Midwest",
    "Michigan": "Midwest",
    "Wisconsin": "Midwest",
    "Iowa": "Midwest",
    "Kansas": "Midwest",
    "Minnesota": "Midwest",
    "Missouri": "Midwest",
    "Nebraska": "Midwest",
    "North Dakota": "Midwest",
    "South Dakota": "Midwest",

    "Delaware": "South",
    "Maryland": "South",
    "Virginia": "South",
    "West Virginia": "South",
    "North Carolina": "South",
    "South Carolina": "South",
    "Georgia": "South",
    "Florida": "South",
    "Kentucky": "South",
    "Tennessee": "South",
    "Mississippi": "South",
    "Alabama": "South",
    "Oklahoma": "South",
    "Texas": "South",
    "Arkansas": "South",
    "Louisiana": "South",

    "Montana": "West",
    "Idaho": "West",
    "Wyoming": "West",
    "Colorado": "West",
    "New Mexico": "West",
    "Arizona": "West",
    "Utah": "West",
    "Nevada": "West",
    "Alaska": "West",
    "Washington": "West",
    "Oregon": "West",
    "California": "West",
    "Hawaii": "West"
}

In [28]:
df_prep["region"] = df_prep["location"].map(state_region)

I grouped the locations into regions with the objective of uncovering insights from a broader perspective.

### Rearrange columns

In [31]:
# age_group column
df_prep.insert(2, 'age_group', df_prep.pop('age_group'))
# region
df_prep.insert(8, 'region', df_prep.pop('region'))
# previous_purchases_group column
df_prep.insert(18, 'previous_purchases_group', df_prep.pop('previous_purchases_group'))

## 6. Analytical Dataset

The prepared dataset retains the original customer-level observations while incorporating the analytical features required for subsequent analysis.

The original variables are preserved, and derived variables are added only where they support the defined analytical requirements.

In [35]:
df_prep.shape

(3900, 21)

The dataset's shape has changed. it now includes 3 additional columns, increasing the total from 18 to 21.

In [60]:
df_prep.columns.tolist()

['customer_id',
 'age',
 'age_group',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount_usd',
 'location',
 'region',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'previous_purchases_group',
 'payment_method',
 'frequency_of_purchases']

In [62]:
df_prep.head()

,customer_id,age,age_group,gender,item_purchased,category,purchase_amount_usd,location,region,size,...,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,previous_purchases_group,payment_method,frequency_of_purchases
0,1,55,55-64,Male,Blouse,Clothing,53,Kentucky,South,L,...,Winter,3.1,Yes,Express,Yes,Yes,14,11-20,Venmo,Fortnightly
1,2,19,18-24,Male,Sweater,Clothing,64,Maine,Northeast,L,...,Winter,3.1,Yes,Express,Yes,Yes,2,0-5,Cash,Fortnightly
2,3,50,45-54,Male,Jeans,Clothing,73,Massachusetts,Northeast,S,...,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,21+,Credit Card,Weekly
3,4,21,18-24,Male,Sandals,Footwear,90,Rhode Island,Northeast,M,...,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,21+,PayPal,Weekly
4,5,45,45-54,Male,Blouse,Clothing,49,Oregon,West,M,...,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,21+,PayPal,Annually

In [64]:
df_prep.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               3900 non-null   int64
 1   age                       3900 non-null   int64
 2   age_group                 3900 non-null   category
 3   gender                    3900 non-null   str
 4   item_purchased            3900 non-null   str
 5   category                  3900 non-null   str
 6   purchase_amount_usd       3900 non-null   int64
 7   location                  3900 non-null   str
 8   region                    3900 non-null   str
 9   size                      3900 non-null   str
 10  color                     3900 non-null   str
 11  season                    3900 non-null   str
 12  review_rating             3900 non-null   float64
 13  subscription_status       3900 non-null   str
 14  shipping_type             3900 non-null   str
 15  discount_applied          3900 non-null   str
 16  promo_code_used           3900 non-null   str
 17  previous_purchases        3900 non-null   int64
 18  previous_purchases_group  3900 non-null   category
 19  payment_method            3900 non-null   str
 20  frequency_of_purchases    3900 non-null   str
dtypes: category(2), float64(1), int64(4), str(14)
memory usage: 586.9 KB

## 7.Validation

The prepared dataset was validated to ensure that the preparation process did not unintentionally alter the established data grain or introduce new data quality issues.

The validation checks covered:

- Row count consistency,
- `Customer ID` uniqueness,
- Duplicate records,
- Missing values
- The resulting derived features.

The prepared dataset retains the customer-level grain established during Data Assessment.

In [78]:
print(df.shape[0], df_prep.shape[0])
print(df.shape[0]==df_prep.shape[0])

3900 3900
True

The information above indicates that no rows were added or removed.

In [81]:
df_prep['customer_id'].is_unique

True

The customer_id column remains unchanged and continues to be unique.

In [88]:
df_prep.isna().sum().sum()

np.int64(0)

All columns are confirmed to have zero missing values

In [117]:
df_prep['age_group'].value_counts(dropna=False)

age_group
25-34    755
45-54    752
55-64    751
35-44    729
18-24    486
65-70    427
Name: count, dtype: int64

In [99]:
df_prep['region'].value_counts(dropna=False)

region
South        1271
West         1018
Midwest       937
Northeast     674
Name: count, dtype: int64

In [101]:
df_prep['previous_purchases_group'].value_counts(dropna=False)

previous_purchases_group
21+      2339
11-20     777
0-5       424
6-10      360
Name: count, dtype: int64

## 8. Summary & Next Steps

The raw dataset was prepared based on the findings and analytical requirements identified during the Data Assessment stage.

No major data cleaning was required since the dataset largely met analytical standards. Only a few analytical features were added to support group-level analysis while preserving the original columns. Overall, the data is clean and fully prepared for Exploratory Data Analysis (EDA).

## Next Steps

The prepared dataset will be used to:

- Explore customer and purchasing behavior,
- Investigate relationships between customer characteristics and
  purchase value,
- Compare customer groups,
- Examine purchasing behavior across product categories, and
- Identify patterns that require further statistical investigation.